version: '3.8'

services:
  storytel-provider:
    build: .
    container_name: storytel-provider
    ports:
      - "3010:3010"
    restart: unless-stopped
    networks:
      - abs_network

networks:
  abs_network:
    external: true
